<script src="assets/templates/js/jquery.min.js"></script><!-- JQUERY.MIN JS -->
<script src="assets/templates/vendor/wow/wow.js"></script><!-- WOW JS -->
<script src="assets/templates/vendor/bootstrap/js/popper.min.js"></script><!-- POPPER.MIN JS -->
<script src="assets/templates/vendor/bootstrap/js/bootstrap.min.js"></script><!-- BOOTSTRAP.MIN JS -->
<script src="assets/templates/vendor/owl-carousel/owl.carousel.js"></script><!-- OWL-CAROUSEL JS -->
<script src="assets/templates/vendor/magnific-popup/magnific-popup.js"></script><!-- MAGNIFIC-POPUP JS -->
<script src="assets/templates/vendor/counter/waypoints-min.js"></script><!-- WAYPOINTS JS -->
<script src="assets/templates/vendor/counter/counterup.min.js"></script><!-- COUNTERUP JS -->
<script src="assets/templates/vendor/imagesloaded/imagesloaded.js"></script><!-- IMAGESLOADED -->
<script src="assets/templates/vendor/masonry/masonry-3.1.4.js"></script><!-- MASONRY -->
<script src="assets/templates/vendor/masonry/masonry.filter.js"></script><!-- MASONRY -->
<script src="assets/templates/vendor/lightgallery/js/lightgallery-all.min.js"></script><!-- LIGHTGALLERY -->
<script src="assets/templates/vendor/bootstrap-select/bootstrap-select.min.js"></script><!-- BOOTSTRAP SELECT -->
<script src="assets/templates/js/dz.carousel.js"></script><!-- OWL-CAROUSEL -->
<script src="assets/templates/js/dz.ajax.js"></script><!-- CONTACT JS  -->
<script src="assets/templates/js/custom.js"></script><!-- CUSTOM JS -->